grammars/yaml.cson

SaltStack uses the YAML syntax to define states (ref: http://docs.saltstack.com/en/latest/topics/tutorials/starting_states.html ), with file extension `.sls`.
This change allows `language-yaml` to recognize those files based on the file extension `.sls`.

Add support for SaltStack states files

---

grammars/yaml.cson
spec/yaml-spec.coffee

Properly handle single leading pound symbols in multiline text

---

grammars/yaml.cson

PagodaBox (https://pagodabox.io/) uses YAML for service configuration. The filename is Boxfile, not *.Boxfile.

Boxfile support (Pagodabox)

---

grammars/yaml.cson
spec/yaml-spec.coffee

Fixes #10
Fixes #30
Fixes #33
Supersedes and closes #36
Supersedes and closes #38
Summary of changes:
* Regular keys now support block-level strings so that specifying `>` or `|` is no longer needed
* Keys with multiple spaces are now properly detected
* Fixed incorrect scopes
Sorry for the crazy yaml-spec.coffee diff...fixing near top-level scopes tends to break a lot of specs.
/cc @flynfish, @stuartpb, and @alexjurkiewicz for testing

Fix and improve multiline strings

---

grammars/yaml.cson
spec/yaml-spec.coffee

Adds support for quoted tag names like `'quoted': stuff`.  In addition, it fixes a boundary issue with `entity.name.tag.yaml` where the tag separator (`:`) was incorrectly being tokenized as the tag name as well.
N/A
Quoted tag names will be highlighted properly; scopes will be more correct.
None.
Fixes #60
---
It is recommended to view the changes separately, by commit.  The second commit is the one that includes the functional changes.

Support quoted tag names

---

grammars/yaml.cson
spec/yaml-spec.coffee

For some reason whenever I work on language-yaml I end up rewriting the whole thing each time.  Oh well.  This PR should probably have been split up into like 10 different ones, but many of the changes depend on the others.
* Pulled standalone `- stuff` (aka tags without a colon) into its own match
* This greatly simplifies the main tag match, meaning that we no longer have three nested non-capturing groups
* Ensure that spaces follow the ending colon (fixes the second part of #53)
* Use a consistent blacklist across tag matches (fixes the first part of …

Another large rewrite

---

grammars/yaml.cson
spec/yaml-spec.coffee

Adds support for local tags (`something: !localTag >`).
None.
See above.
None.
Fixes #65.
@danilobuerger the YAML spec is a bit unclear on whether or not local tags can be used in normal keys, like the following:
```yaml
key: !tag
- stuff
```
Would you happen to know if that's valid syntax or not?

Tokenize and handle local tags correctly

---

grammars/yaml.cson
spec/yaml-spec.coffee

YAML does not treat backslash sequences as escape characters in single-quoted strings.  The only recognized escape character is escaping a single quote via `''`.  So, this PR removes escape character highlighting for single-quoted strings and replaces it with the special-case single-quote escape.
None.
In line with the spec.
None.
Fixes #67
Thanks for the report @trejkaz!

Don't match escape characters in single quotes

---

grammars/yaml.cson

From https://stylelint.io/user-guide/configuration/
> The `.stylelintrc` file (without extension) can be in JSON or YAML format.
Note that `.stylintrc` != `.stylelintrc` atom/language-json#56

Add '.stylelintrc' file support

---

grammars/yaml.cson
spec/yaml-spec.coffee

YAML is tricky because it supports multiline strings using regular tags.  As long as the next line is indented more than the tag, it'll be counted as part of the string.  In previous PRs I implemented the multiline support, but without the indentation requirement.  This PR properly implements indentation checks so that we don't attempt to tokenize _everything_ until the next tag as scalar content.  This fixes embedding (valid) YAML in other grammars, such as GFM.
In addition, the end document marker `...` has been added.
None.
The immediate benefits …

Fix multiline strings and add document end marker support

---

grammars/yaml.cson
spec/yaml-spec.coffee

Escape sequence tokenization now follows the rules laid out in http://yaml.org/spec/1.2/spec.html#id2776092.
None.
Correct tokenization for escape sequences.
While writing a hex or unicode escape sequence, error highlighting will occur until you finish the sequence.
Fixes #75

Add more support for escape sequences

---

grammars/yaml.cson

The default YAMLLint configuration file is `.yamllint`.
The configuration itself is YAML.
http://yamllint.readthedocs.io/en/latest/configuration.html

Add support for .yamllint filetype

---

grammars/yaml.cson
spec/yaml-spec.coffee

Also tokenize ~ as an alternative to null
Tokenize `true`, `false`, `null`, `True`, `False`, `Null`, `TRUE`, `FALSE`, `NULL`, `~` as constants per the [YAML spec](http://yaml.org/spec/1.2/spec.html#id2805071).
Tokenizing other variants, such as `yes` and `no` (#81), but decided not to do so as those are not recognized by the spec.
Closer to the spec.
None.
#81

Tokenize uppercase variants of true, false, null

---

grammars/yaml.cson
spec/yaml-spec.coffee

Allow quotes inside and after a key if it does not start with a quote.
The grammar was explicitly performing additional, incorrect behavior, so removing this behavior was the only solution.
Compliance with the YAML spec for keys and correct syntax highlighting of keys.
None.
Closes #83

Allow quotes inside of unquoted keys

---

grammars/yaml.cson

This pull request changes 2 regular expressions in an attempt to make the grammar PCRE-compatible. While Atom uses an Oniguruma engine, github.com (which rely on this grammar for YAML highlighting) uses a PCRE-based engine. The two engines interpret `\h` and `\N` differently.
None considered.
Make the grammar PCRE-compatible. In particular, github.com uses a PCRE engine when it interprets this grammar.
Example for the second change (escaping `N`): [before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fpchaigno%2Flanguage-yaml%2Fblob%2Fmaster%2Fgrammars%2Fyaml.cson&grammar_text=&code_source=from-text&code_url=&code=test%3A+%22some+string%5C_with+and+escape+sequence%22) and …

Make the grammar PCRE compatible

---

grammars/yaml.cson

Simple fix to allow TODO injections to work.  Same as https://github.com/atom/language-coffee-script/commit/ad0aa553d8f91ca1c4605da0bce5bcaf66c3e2bd
Fixes #89

Use begin/end match for comments

---

grammars/yaml.cson
spec/yaml-spec.coffee

There are three issues addressed in this pull request.
1. Comments would be ignored in all parts of a multiline block, including the tag definition itself.  language-yaml now tokenizes comments following a tag definition.
2. Multiline tag definitions would override the comment pattern, resulting in a comment receiving incorrect tag highlighting.  The multiline tag definition regexes have been tweaked to match other similar regexes.
3. Key-like structures in multiline blocks would be tokenized as actual key structures rather than a continuation of the …

Address multiple issues with comments and multiline tags

---

grammars/yaml.cson

I've added `ksy` extension to the file `grammars/yaml.cson` so that [Kaitai](http://kaitai.io)'s files can be recognized as `yaml` files.
Kaitai's format specification files will be automatically recognized as yaml files. 
Another application could use `ksy` extension for files which format is not yaml.
None.

Adding Kaitai `.ksy` extension as `yaml` file.

---

grammars/yaml.cson
spec/yaml-spec.coffee

Tokenize keys at the same level of indentation after an unquoted block section.  The diff looks busy, but really all I did was flip the two block patterns so that the one matching dashes has precedence.  There's also a minor optimization to tag name matching where it will now stop upon reaching a colon rather than EOL.
None.
Another YAML bug squashed.
Hopefully none - I feel like this makes a ton more sense than trying to keep the previous order where for some reason the less-specific non-dash version was matched before the more-specific dash version. …

Tokenize keys after an unquoted block

---

grammars/yaml.cson
spec/yaml-spec.coffee

The previous numeric implementation was custom-written and seems to combine YAML's spec with a bit of Java's.  This rewrite makes it conform to the official YAML spec at http://www.yaml.org/spec/1.2/spec.html#id2805071.  Some changes include:
* Removal of support for `3.0f`-style floats
* Removal of support for `0X2`-style hexadecimal integers (`0x2` is still supported)
* Octal support
* Positive/number integer/float support
* Infinity/NaN support
Keep the existing implementation but tweak it to support the additions listed above.  I rejected this because …

Rework number tokenization according to the spec
